services:
  dot_ch_radio:
    build:
      context: .
      dockerfile: Dockerfile
    image: dotchradio:latest
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"
    container_name: dot_ch_radio
    volumes:
      - ~/dockers/dot-ch-radio/volume:/app/volume
    restart: unless-stopped
