name: dot_ch_radio

services:
  dot_ch_radio:
    build:
      context: .
      dockerfile: Dockerfile
    image: dotchradio:latest
    environment:
      TELEGRAM_API_ID: "${TELEGRAM_API_ID:-}"
      TELEGRAM_API_HASH: "${TELEGRAM_API_HASH:-}"
      OPENWEATHER_API_KEY: "${OPENWEATHER_API_KEY:-}"
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"
    container_name: dot_ch_radio
    volumes:
      - ~/dockers/dot_ch_radio/volume:/app/volume
      - ~/dockers/dot_ch_radio/config:/app/config
      - ~/dockers/dot_ch_radio/content:/app/content
    restart: unless-stopped
